Algoritmo "multiplos"

//algoritmo para determinar se dois números são múltiplos//
Var

   x1, x2 : inteiro


Inicio

      escreva("Digite dois numeros inteiros: ")
      leia(x1)
      leia(x2)
      
      
      se (x1 % x2 = 0) ou (x2 % x1 = 0) entao
      escreva("sao multiplos")
      
      senao
      escreva("Nao sao multiplos")
      
      fimse
      


Fimalgoritmo